version: "3"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "qwe"
      POSTGRES_DB: "ativiadb"
    ports:
      - "5444:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d  # Place .sql scripts here for initialization
      - ./csv:/csv  # Mount .csv directory for loading files at runtime
  
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "andre@ativia.com"
      PGADMIN_DEFAULT_PASSWORD: "qwe"
    ports:
      - "6543:80"
    depends_on: 
      - postgres
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
    driver: bridge